# Generated by Django 5.1.6 on 2025-03-05 20:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.custom_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('eliminado', 'Eliminado')], default='pendiente', max_length=20)),
            ],
        ),
    ]
