# Generated by Django 5.1.6 on 2025-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('categorized', 'Procesado'), ('deleted', 'Eliminado')], default='pendiente', max_length=20),
        ),
    ]
