# Generated by Django 5.1.6 on 2025-03-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filemetadatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('categorized', 'Procesado'), ('deleted', 'Eliminado')], default='pending', max_length=20),
        ),
    ]
