# Generated by Django 5.1.6 on 2025-12-08 05:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_uploadedfile_file_location_alter_uploadedfile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.custom_upload_path
            ),
        ),
    ]
